import './globals.css'
import { Aclonica } from 'next/font/google'

const aclonica = Aclonica({ subsets: ['latin'],weight: '400' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={aclonica.className}>{children}</body>
    </html>
  )
}
